[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@chainlink/contracts/src/v0.8/interfaces=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces',
  '@chainlink/contracts/src/v0.8/vrf=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/v0.8',
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@thirdweb-dev/contracts=lib/contracts/contracts',

]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
